### PR TITLE
Fix problem with filename ext (ticket: #4765)

### PR DESCRIPTION
**Pull request by scipe**
Hi guys. This is just fix for this ticket: https://github.com/keystonejs/keystone/issues/4765

I am using keystone on 3 different servers and always I have this problem with saving files. This solution working everythere.

### CODE REVIEW

**Comment by laurenskling** [comment]
@autoboxer @gautamsi , I've never used storage, can you take a look?

**Comment by scipe** [comment]
Hello guys @autoboxer @gautamsi. Any chance to check this PR on this / next week?

**Comment by gautamsi** [comment]
I am fine with the changes

**Comment by scipe** [comment]
Up :)

**Comment by scipe** [comment]
Guys?

**Comment by scipe** [comment]
End of November

**Comment by scipe** [comment]
😢

**Pull request merged**
