### PR TITLE
add middleName field in Types.Name

### PR DESCRIPTION
**Pull request by rulab**
## Description of changes
Add option middleName:bool in Types.Name field (default=false)
If middleName isset and equal true, AdminUI render third input for enter middle name of persone

## Testing
 - [ ] Create new model with two fields with type: Types.Name. One with option middleName as true and another one without this option 
 - [ ] Create new instance of this model in AdminUI
 - [ ] Please confirm: first field has input for middle name
 - [ ] Please confirm: second field does not suggest input for middle name

### CODE REVIEW

**Comment by laurenskling** [comment]
I love the effort you have put in, writing all the tests included. 
I'm unsure though, if the middle name needs to be included in the Name `type` in the core of Keystone. You can easily write your own `type` and use that. (even release it on NPM)

What would you say @autoboxer , @JedWatson , @gautamsi

**Comment by autoboxer** [comment]
I can certainly see the value of this, but I can see the argument against it as well to keep the fields simple and clean.  I think enough people would find this useful that it warrants inclusion, however, I'm also curious how @JedWatson feels about it.

**Comment by rulab** [comment]
I believe that this may be useful to many people, but in order not to overload your admin UI, I made this field optional.

**Comment by autoboxer** [comment]
I just did a deeper review and like how you implemented it as optional @rulab.  Thank you for taking the time to write tests as well.  I marked this for inclusion in a future release, and barring @JedWatson or another team member from finding issue, I'll push to include it with the next release outside of test fixes.

**Comment by rulab** [comment]
@autoboxer thanks

**Comment by laurenskling** [comment]
hey @rulab , this PR was widely discussed in our last maintenance meeting. We have some issues regarding the schema always being extended with middleName and safeguarding some functions and empty values.
We would like to invite you to one of our weekly meetings to elaborate on our concerns. 
We have a weekly meeting on sunday at 12:00 GMT, would you be able to join sometime?
We are also active on Slack: http://community.keystonejs.com/

**Pull request closed without merging**
